/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
            Scanner scanner = new Scanner(System.in);
            String choice;

            do {
                System.out.println("----------------------------------------------");
                System.out.println("[과제관리 시스템]");
                System.out.println();
                System.out.println("1. 과제");
                System.out.println("2. 게시글");
                System.out.println("3. 도움말");
                System.out.println("4. 종료");
                System.out.print("> ");
                choice = scanner.nextLine();

                switch (choice) {
                    case "1":
                        System.out.println("과제입니다.");
                        break;
                    case "2":
                        System.out.println("게시글입니다.");
                        break;
                    case "3":
                        System.out.println("도움말입니다.");
                        break;
                    case "4":
                        System.out.println("종료합니다.");
                        break;
                    case "menu":
                        break;
                    default:
                        System.out.println("잘못된 입력입니다.");
                }
            } while (!choice.equals("4"));

            scanner.close();
        }
    }



